FROM golang:1.26-alpine

RUN addgroup -g 1000 go && adduser -D -h /home/go -G go -u 1000 go

WORKDIR /home/go

COPY go.mod go.sum ./
RUN go mod download

COPY --chown=go:go . .

USER go

CMD ["go", "test", "-v", "-cover", "-count=1", "-p", "1", "./..."]
